# Phase 1: Team Pre-training with Strategy Conditioning
#
# This configuration enables diverse behavior pre-training using:
#   - FiLM conditioning: h' = gamma(c) * h + beta(c) 
#   - Discriminator: predicts strategy code c from trajectory
#   - Intrinsic reward: r_intrinsic = log q(c | trajectory)
#
# Architecture:
#   - Encoder: MLP producing embedding h_t
#   - FiLM: conditions hidden features on strategy code c
#   - Policy: pi(a | h'_t) where h'_t = FiLM(h_t, c)
#   - Discriminator: GRU over (positions, actions) -> predicts c
#
# Training Loop:
#   1. Sample strategy code c ~ Categorical(K) per episode
#   2. Rollout team for T steps with policy conditioned on c
#   3. Compute intrinsic reward: r_intrinsic = alpha * log q(c | trajectory)
#   4. PPO update on r_total = r_game + r_intrinsic
#   5. Supervised update of discriminator to predict c

expr_group: gr_football
expr_name: full_game_5_vs_5_hard_mappo_phase1
log_dir: ./logs
seed: 0
eval_only: False

distributed:
  use: False
  auto_connect:
  auto_copy:
  nodes:
    master:
      ip: "auto"
    workers:      
      - ip:

framework:
  name: "psro"
  max_rounds: 1
  meta_solver: "nash"
  sync_training: True
  stopper:
    type: "win_rate_stopper"
    kwargs:
      min_win_rate: 1.0
      max_steps: 700

agent_manager:
  num_agents: 2
  share_policies: False

evaluation_manager:
  num_eval_rollouts: 1

policy_data_manager:
  update_func: "gr_football" 
  fields:
    payoff:
      type: "matrix"
      missing_value: -100 
    score:
      type: "matrix"
      missing_value: -100 
    win:
      type: "matrix"
      missing_value: -100 
    lose:
      type: "matrix"
      missing_value: -100 
    my_goal:
      type: "matrix"
      missing_value: -100 
    goal_diff:
      type: "matrix"
      missing_value: -100 
        
monitor:
  type: "local"
  distributed:
    resources:
      num_cpus: 1
      resources:
        - ["node:${distributed.nodes.master.ip}",0.01]

rollout_manager:
  distributed:
    resources:
      num_cpus: 1
      resources:
        - ["node:${distributed.nodes.master.ip}",0.01]
  num_workers: 5
  seed: 12345
  saving_interval: 20
  batch_size: ${rollout_manager.num_workers}
  eval_batch_size: 16
  eval_freq: 100
  rollout_metric_cfgs:
    reward:
      type: "sliding"
      window_size: 20
      init_list: [-10000]
    win:
      type: "sliding"
      window_size: 20
      init_list: [0,0,0,0,0]
  worker:
    distributed:
      resources:
        num_cpus: 1
    rollout_length: 3001
    eval_rollout_length: 3001
    sample_length: 0
    padding_length:
    # NOTE: flash_token DISABLED for Phase 1
    # We want strategy_code to be THE conditioning signal
    # Having both creates semantic confusion
    flash_token:
      enabled: False
      dim: 0
      mode: "off"
      std: 1.0
    # ===== Phase 1: Strategy Conditioning =====
    strategy_conditioning:
      enabled: True                 # Enable Phase 1 training
      num_strategies: 8             # K = 8 discrete strategy codes
      intrinsic_reward_coef: 0.1    # alpha coefficient for intrinsic reward
      # Window size for discriminator (sweet spot: 20-50 steps)
      # Too short (5): only sees velocity/jitter
      # Too long (100): gradient propagation is hard
      window_size: 32               # ~3 seconds at 10Hz
    rollout_func_name: "rollout_func"
    episode_mode: 'traj'
    envs:
      - cls: "gr_football"
        id_prefix: "gr_footbal"
        scenario_config:
          env_name: "benchmark_full_game_5_vs_5_hard"
          number_of_left_players_agent_controls: 4
          number_of_right_players_agent_controls: 1
          representation: "raw"
          rewards: "scoring,checkpoints"
          stacked: False
          logdir: '/tmp/football/malib_phase1'
          write_goal_dumps: False
          write_full_episode_dumps: False
          render: False
          other_config_options:
            action_set: v2
        reward_config:
          goal_reward: 0
          official_reward: 1
    credit_reassign:
    decaying_exploration:
      init_noise: 0.1
      total_epoch_to_zero: 2000
      interval: 400

training_manager:
  distributed:
    resources:
      num_cpus: 1
      resources:
        - ["node:${distributed.nodes.master.ip}",0.01]
  master_addr: "127.0.0.1"
  master_port: "12775"
  local_queue_size: 1
  batch_size: ${rollout_manager.batch_size}
  num_prefetchers: 1
  data_prefetcher:
    distributed:
      resources:
        num_cpus: 1
  num_trainers: 1
  update_interval: 1
  gpu_preload: False
  trainer:
    distributed:
      resources:
        num_cpus: 1
        num_gpus: 0
        resources:
          - ["node:${distributed.nodes.master.ip}",0.01]
    optimizer: "Adam"
    actor_lr: 5.e-4
    critic_lr: 5.e-4
    backbone_lr: 5.e-4
    discriminator_lr: 1.e-3        # Discriminator learning rate
    opti_eps: 1.e-5
    weight_decay: 0.0
    lr_decay: False
    lr_decay_epoch: 2000
    device: "cpu"

data_server:
  distributed:
    resources:
      num_cpus: 1
      resources:
        - ["node:${distributed.nodes.master.ip}",0.01]
  table_cfg:
    capacity: 1000
    sampler_type: "lumrf"
    sample_max_usage: 1
    rate_limiter_cfg:
      min_size: ${training_manager.batch_size}
  read_timeout: 1

policy_server:
  distributed:
    resources:
      num_cpus: 1
      resources:
        - ["node:${distributed.nodes.master.ip}",0.01]

populations:
  - population_id: default
    algorithm:
      name: "MAPPO"
      model_config:
        model: "gr_football.passandscore_factorized"
        initialization:
          use_orthogonal: True
          gain: 1.
        backbone: {}
        actor:
          network: mlp
          layers:
            - units: 128
              activation: ReLU
            - units: 128
              activation: ReLU
          output:
            activation: False
        critic:
          network: mlp
          layers:
            - units: 128
              activation: ReLU
            - units: 128
              activation: ReLU
          output:
            activation: False

      custom_config:
        FE_cfg:
          num_players: 10
        sub_algorithm_name: MAPPO
        num_agents: 4
        
        # CTDE Configuration
        factorized_actor_use_global: False
        factorized_critic_use_local: False
        factorized_critic_use_pooled: True
        # flash_token disabled for Phase 1 (strategy_code is the only conditioning)
        factorized_actor_use_flash: False
        factorized_critic_use_flash: False
        flash_dim: 0
        
        # ===== Phase 1: Strategy Conditioning (ENABLED) =====
        training_phase: "phase1"            # Explicitly set Phase 1 mode
        use_strategy_conditioning: True     # Enable FiLM conditioning
        num_strategies: 8                   # K = 8 discrete strategy codes
        strategy_embed_dim: 32              # FiLM embedding dimension
        discriminator_hidden_dim: 64        # Discriminator GRU hidden size
        # Window size (sweet spot: 20-50 for GRF tactics)
        discriminator_window_size: 32       # ~3 seconds at 10Hz
        discriminator_use_actions: True     # Include actions in discriminator input
        # Batch size for discriminator training (independent of num_workers)
        # Larger = more stable gradients. 64-128 recommended.
        discriminator_batch_size: 64
        
        other_clip_param: 0.125

        gamma: 0.995
        use_cuda: False
        device: "cpu"
        use_q_head: False
        ppo_epoch: 10
        num_mini_batch: 2
        
        return_mode: new_gae
        gae:
          gae_lambda: 0.95
        vtrace:
          clip_rho_threshold: 1.0
          clip_pg_rho_threshold: 100.0

        use_rnn: False
        rnn_layer_num: 1
        rnn_data_chunk_length: 16

        use_feature_normalization: True
        use_popart: True
        popart_beta: 0.99999

        entropy_coef: 0.005
        clip_param: 0.2

        use_modified_mappo: False

      policy_init_cfg:
        agent_0:
          new_policy_ctr_start: -1
          init_cfg:
            - condition: "==0"
              strategy: random
              policy_id: 
              policy_dir:
          initial_policies:

        agent_1:
          new_policy_ctr_start: -1
          init_cfg:
            - condition: "==0"
              strategy: pretrained
              policy_id: built_in
              policy_dir: light_malib/trained_models/gr_football/5_vs_5/built_in
          initial_policies:

